services:
  chat-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      chat-db:
        condition: service_healthy
    networks:
      - chat-net
    env_file: ".env"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=chat-db;Port=5432;Database=UserDb;Username=admin;Password=${POSTGRES_PASSWORD};
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=chat-app
      - JWT__Audience=chat-app-users
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets

  chat-db:
    image: postgres:17
    ports:
      - 5432:5432
    env_file: ".env"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: UserDb
    networks:
      - chat-net
    volumes:
      - chat-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d UserDb"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  chat-net:
    driver: bridge

volumes:
  chat-volume:
